# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b0a7e42b222cfec6ea544e3b07fc16c4e35ef3a422f728b8e2fd11fc0fb2d34e1be3df030a6ea8bb209f4aba216cd2599fbdeff44b4cdab6eb55a88c903823

test:
  secret_key_base: 2f8832037f9be106ed3c5a7bb8aeb1238844e613e0f3c3fa98060dd155a0737dcfbbf119885cdde3fd936e7864d29765495d0fe73f1e34948fdbb36bfca61a37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
